# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: deploy CI jar to OSS

on:
  push:
    branches: [ issue_2336 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: init mysql
        run: |
          sudo /etc/init.d/mysql start
          export MYSQL_PWD=root
          for i in *.sql;do echo $i;mysql -h localhost -uroot < $i;done
        working-directory: support-files/sql
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up GPG
        run: |
          echo ${{ github.workspace }}
          echo ${SIGNING_KEY} | awk '{gsub(/\\n/,"\n")}1'| gpg --dearmor > ${{ github.workspace }}/secretKeyRingFile.gpg
          ls -al ${{ github.workspace }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        working-directory:
      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        env:
          build_mavenRepoDeployUrl: "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
          build_mavenRepoUsername: ${{ secrets.SONATYPE_USERNAME }}
          build_mavenRepoPassword: ${{ secrets.SONATYPE_PASSWORD }}
        with:
          gradle-version: 4.8.1
          build-root-directory: src/backend/ci
          arguments: publish -DmavenRepoUrl="http://maven.aliyun.com/nexus/content/groups/public/" -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password="${{ secrets.SIGNING_PASSWORD }}" -Psigning.secretKeyRingFile="${{ github.workspace }}/secretKeyRingFile.gpg"
